[package]
name = "discord-banner-attempt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.tokio-util]
version = "0.6"
features = ["time"]

[dependencies.tokio-stream]
version = "0.1"

# [dependencies.serenity]
# version = "0.10"
# default-features = false
# features = [
#     "builder",
#     "cache",
#     "collector",
#     "client",
#     "gateway",
#     "http",
#     "model",
#     "utils",
#     "rustls_backend",
#     "unstable_discord_api",
# ]

[dependencies.dotenv]
version = "0.15"

[dependencies.poise]
git = "https://github.com/kangalioo/poise"
branch = "master"
features = ["collector"]

[dependencies.log]
version = "0.4"

[dependencies.env_logger]
version = "0.9"

[dependencies.url]
version = "2"