[package]
name = "discord-banner-bot"
version = "0.7.0"
edition = "2024"
authors = ["Andre Julius <noromoron@gmail.com>"]
license-file = "LICENSE"
description = "Discord bot for changing server banners on a customizable timer"
homepage = "https://github.com/NotNorom/discord-banner-bot"
repository = "https://github.com/NotNorom/discord-banner-bot"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
dev = []

[profile.release]
debug = true

[dependencies]
async-repeater = "1.0.0"
base64 = "0.23.1"
bytes = "1.12.1"
chrono = "0.4"
clap = { version = "4.6.7", features = ["derive"] }
config = { version = "0.15", default-features = false, features = ["toml"] }
fred = { version = "10.1.0", default-features = false, features = [
    "i-std",
    "i-sets",
    "i-hashes",
] }
poise = "=0.7.0"
rand = "0.10.3"
reqwest = { version = "0.13.5", default-features = false, features = [
    "json",
    "native-tls-vendored",
    "stream",
] }
serde = "1.0.229"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = [
    "rt-multi-thread",
], default-features = false }
tokio-stream = "0.1.19"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
    "tracing-log",
    "env-filter",
    "parking_lot",
] }
url = "2.5.8"

[patch.crates-io]
# async-repeater = { git = "https://github.com/NotNorom/async-repeater.git" }
poise = { git = "https://github.com/serenity-rs/poise.git", rev = "e762abbdf210ef77ab46187f5d9710d7fca22c3e" } #, branch = "serenity-next" }
# poise = { path = "/home/norom/Documents/Code/poise" }
# serenity = { git = "https://github.com/serenity-rs/serenity" }
# serenity = { path = "/home/norom/Documents/Code/serenity" }

#[patch."https://github.com/serenity-rs/serenity.git"]
# serenity = { path = "/home/norom/Documents/Code/serenity" }

# [patch."https://github.com/serenity-rs/serenity.git"]
serenity = { git = "https://github.com/serenity-rs//serenity", rev = "4da73fa9f73f87174f08f2dd27bf8a1245caca23" }
