[package]
name = "discord-banner-bot"
version = "0.5.1"
edition = "2021"
authors = ["Andre Julius <noromoron@gmail.com>"]
repository = "https://github.com/NotNorom/discord-banner-bot"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
dev = []


[profile.release]
debug = true


[dependencies]
thiserror = "1.0.48"
anyhow = "1.0.75"
imgurs = "0.11.2"
tokio-stream = "0.1.14"
url = "2.4.1"
rand = "0.8.5"
base64 = "0.21.4"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [
    "tracing-log",
    "env-filter",
    "parking_lot",
] }
fred = { version = "6.3.1", default-features = false, features = [
    "pool-prefer-active",
] }
poise = "0.5.6"
config = { version = "0.13.3", default-features = false, features = ["toml"] }
serde = "1.0.188"
once_cell = "1.18.0"
reqwest = { version = "0.11.20", default-features = false, features = [
    "json",
    "native-tls-vendored",
] }
tokio = { version = "1.32.0", features = [
    "rt-multi-thread",
], default-features = false }
tokio-util = { version = "0.7.8", features = ["time"] }
async-repeater = { git = "https://github.com/NotNorom/async-repeater.git" }
# async-repeater = { path = "/home/norom/Documents/Code/async-repeater" }

