[package]
name = "discord-banner-bot"
version = "0.2.2"
edition = "2021"
authors = ["Andre Julius <noromoron@gmail.com>"]
repository = "https://github.com/NotNorom/discord-banner-bot"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"
anyhow = "1.0.66"
imgurs = "0.11.0"
tokio-stream = "0.1.11"
dotenv = "0.15.0"
env_logger = "0.10.0"
url = "2.3.1"
rand = "0.8.5"
base64 = "0.13.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
fred = "5.2.0"

[dependencies.tokio]
version = "1.23.0"
features = ["full"]

[dependencies.tokio-util]
version = "0.7.4"
features = ["time"]

[dependencies.poise]
version = "0.5.1"
features = ["collector"]

[dependencies.reqwest]
version = "0.11.13"
features = ["json"]
