[package]
name = "discord-banner-bot"
version = "0.4.0"
edition = "2021"
authors = ["Andre Julius <noromoron@gmail.com>"]
repository = "https://github.com/NotNorom/discord-banner-bot"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
dev = []


[profile.release]
debug = true


[dependencies]
thiserror = "1.0.40"
anyhow = "1.0.71"
imgurs = "0.11.1"
tokio-stream = "0.1.14"
url = "2.3.1"
rand = "0.8.5"
base64 = "0.21.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [
    "tracing-log",
    "env-filter",
    "parking_lot",
] }
fred = { version = "6.2.0", default-features = false, features = [
    "pool-prefer-active",
] }
poise = "0.5.5"
config = { version = "0.13.3", default-features = false, features = ["toml"] }
serde = "1.0.160"
once_cell = "1.17.1"
reqwest = { version = "0.11.17", default-features = false, features = [
    "json",
    "native-tls-vendored",
] }
tokio = { version = "1.28.0", features = [
    "rt-multi-thread",
], default-features = false }
tokio-util = { version = "0.7.8", features = ["time"] }
