services:
  bot:
    build: .
    networks:
      - dbb
    depends_on:
      - db
    volumes:
      - ./settings.toml:/conf/settings.toml:ro
  db:
    image: docker.io/redis:alpine
    networks:
      - dbb

networks:
  dbb:
